version: "3.9"
services:
  reports:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abcall-reports-api
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "3008:3008"
    env_file:
      - .env
    tty: true