name: Merge to Develop
on:
    pull_request:
      types:
        - closed  
jobs:
  merge-from-develop:
    name: Merge from develop
    runs-on: ubuntu-latest
    steps:
    - name: Merge ${{ github.ref }} -> develop
      if: github.event.pull_request.merged == true && (github.head_ref == 'feature/*' || github.head_ref == 'hotfix/*' || github.head_ref == 'release/*' || github.head_ref == 'bugfix/*')
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: ${{ github.ref }}

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: merge-from-develop
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Environment configuration
      uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
    - name: Running tests 🧪
      id: test-running-id
      run: |
        make run-tests
      env:
        ENVIRONMENT: test
    - name: Validate results with errors
      if: ${{ failure() }}
      env:
        ERROR_MESSAGE: One or several tests failed 🔴
      run: echo "::set-output name=answer::${ERROR_MESSAGE}"
    - name: Validate result without errors
      if: ${{ success() }}
      env:
        MESSAGE_SUCCESS: All the tests were success
      run: echo "::set-output name=answer::${MESSAGE_SUCCESS}"
    - name: Coverage calculation 📊
      id: Coverage
      run: |
        make run-tests-coverage
         
  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Mezcla ${{ github.ref }} -> develop
      if: github.event.pull_request.merged == true && (github.head_ref == 'feature/*' || github.head_ref == 'hotfix/*' || github.head_ref == 'release/*' || github.head_ref == 'bugfix/*') && success()
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: ${{ github.ref }}
        target-branch: develop

  tag:
    name: Create a tag
    runs-on: ubuntu-latest
    needs: merge
    steps:
    - name: create a tag for last develop commit
      uses: actions/checkout@v2
      with:
        source-branch: develop
        fetch-depth: 0
    - name: Initialize git
      run: git init
      if: ${{ success() }}
    - name: Initialize mandatory git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com
    - name: Create a Tag
      run: |
        git checkout develop
        git tag merge-to-develop-$GITHUB_RUN_NUMBER
    - name: Push tag
      run: git push origin merge-to-develop-$GITHUB_RUN_NUMBER